version: 0.2
env:
  variables:
    DOCKER_DRIVER: overlay
    GRAILS_VERSION: 1.3.8
    ETUDE_VERSION: 1.0.0
    REPOSITORY_URI: 754835769352.dkr.ecr.eu-central-1.amazonaws.com
    JAVA_OPTS: -Dstringchararrayaccessor.disabled=true
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - chmod +x ./build.sh
      - docker run --rm -v ${PWD}/:/app -v ~/.grails:/root/.grails -e CI_JOB_ID=$CI_JOB_ID -v ~/.ivy2:/root/.ivy2/ $REPOSITORY_URI/arkilog/cloud/etude-builder
      - docker build -t $REPOSITORY_URI/arkilog-beta-etude:$ETUDE_VERSION .
      - docker push $REPOSITORY_URI/arkilog-beta-etude:$ETUDE_VERSION
cache:
    paths:
      - ~/.ivy2
      - ~/.grails
