version: '3.1'

services:
  postgres:
    image: postgres:13.1
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: etude
      POSTGRES_PASSWORD: etude
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8088:8081"
    links:
      - postgres:postgres  # my database container is called postgres, not db
    environment:
      - DATABASE_URL=postgres://etudesaas:etudesaas@postgres:5432/etudesaas?sslmode=disable
    depends_on:
      - postgres
